# Generated by Django 2.2.3 on 2019-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uniq_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
