# Generated by Django 2.2.3 on 2019-11-11 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two', '0002_auto_20191111_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodType', models.CharField(max_length=120)),
                ('storgeArea', models.CharField(max_length=120)),
                ('dateOfStorage', models.DateField()),
                ('booked', models.BooleanField(blank=True, default=False, null=True)),
                ('bookedBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to=settings.AUTH_USER_MODEL)),
                ('donatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
