# Generated by Django 2.2.3 on 2019-11-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two', '0004_auto_20191111_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='bookedBy',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedBlood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Storage')),
                ('bookedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
