# Generated by Django 2.2.3 on 2019-10-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_HR',
            field=models.BooleanField(default=False),
        ),
    ]
